<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/ProxyWin.Windows/ProxyWin.Windows.csproj" /></ItemGroup>
  <ItemGroup><Content Include="../../driver/*" Link="driver/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" Exclude="../../driver/README.md" /></ItemGroup>
</Project>
